###########################
######## ACCURACY #########
###########################

### RANK GRADUATION ACCURACY (RGA) MEASURE ###
# Function for the RGA (Rank Graduation Accuracy) measure computation
# Inputs: y -> observed target variable values; yhat -> predictions generated by the applied selected model

RGA<-function(y,yhat){   
  ryhat<-rank(round(yhat,4),ties.method="min") # ranks of the predicted values
  support<-tapply(y,ryhat,mean) # replace the observed target variable value corresponding to the same predictive values with their mean 
  rord<-c(1:length(y))   
  for(jj in 1:length(y))
  {
    rord[jj]<-support[names(support)==ryhat[jj]] 
  }  
  ystar<-rord[order(yhat)] # re-order the observed target variable values with respect to the corresponding predicted values
  I<-1:length(y) 
  conc<-2*sum(I*ystar) # first term of the RGA numerator (concordance)
  dec<-2*sum(I*sort(y,decreasing=TRUE)) # second term of the RGA numerator and denominator (dual Lorenz)
  inc<-2*sum(I*sort(y)) # first term of the RGA denominator (Lorenz)
  RGA<-(conc-dec)/(inc-dec)
  RGA
}

####################################################################################################################################################################################################################

# RGA based test for comparing the predictive accuracy of a reduced model with that of a more complex model
library(bootstrap) # package needed for the jackknife estimation

# y -> vector including the observed target variable values
# yhat_rm -> vector including the predicted values provided by the reduced model
# yhat_cm -> vector including the predicted values provided by the complex model

n<-length(y) # number of observations in the test dataset

jack.mat<-data.frame(cbind(y,yhat_rm,yhat_cm)) # build a dataframe with the vector of the target variable (y) and the vectors of the predicted models (yhat_rm and yhat_cm)

attach(jack.mat)

delta<-function(z,jack.mat){RGA(jack.mat[z,1],jack.mat[z,3])-RGA(jack.mat[z,1],jack.mat[z,2])} # function for computing the difference between the RGA associated with the two compared models

results<-jackknife(1:n,delta,jack.mat) # results related to the Jackknife estimation
names(results) # assign the names to the elements of the object "results"

se<-results[1]$jack.se # standard error of the jackknife estimator
z<-(RGA(y,yhat_cm)-RGA(y,yhat_rm))/se # test statistic
p_value<-2*pnorm(-abs(z)) # p-value

###########################
######## SECURITY #########
###########################
### RANK GRADUATION ROBUSTNESS (RGR) MEASURE ###

# Function for the RGR (Rank Graduation Robustness) measure computation
# Inputs: yhat -> predictions generated by the applied selected model on non-perturbed data; yhat_pert -> predictions generated by the applied selected model on pertirbed data

RGR<-function(yhat,yhat_pert){   
  ryhat_pert<-rank(round(yhat_pert,4),ties.method="min") # ranks of the predicted values on perturbed data
  support<-tapply(yhat,ryhat_pert,mean) # replace the observed predicted values corresponding to the same predictive values on perturbed data with their mean 
  rord<-c(1:length(yhat))   
  for(jj in 1:length(yhat))
  {
    rord[jj]<-support[names(support)==ryhat_pert[jj]] 
  }  
  yhatstar<-rord[order(yhat_pert)] # re-order the predicted values with respect to the corresponding predicted values on perturbed data
  I<-1:length(yhatstar) 
  conc<-2*sum(I*yhatstar) # first term of the RGR numerator (concordance)
  dec<-2*sum(I*sort(yhat,decreasing=TRUE)) # second term of the RGR numerator and denominator (dual Lorenz)
  inc<-2*sum(I*sort(yhat)) # first term of the RGR denominator (Lorenz)
  RGR<-(conc-dec)/(inc-dec)
  RGR
}

####################################################################################################################################################################################################################

# RGR based test for comparing the robustness of a model with that of a further compared model
library(bootstrap) # package needed for the jackknife estimation

# yhat_mod1 -> vector including the predicted values by the first model in the case of non-perturbed data
# yhat_mod2 -> vector including the predicted values by the second model in the case of non-perturbed data

# yhat_pert_mod1 -> vector including the predicted values provided by the first model in the case of perturbed data
# yhat_pert_mod2 -> vector including the predicted values provided by the second model in the case of perturbed data

n<-length(yhat_mod1) # number of observations in the test dataset

jack.mat<-data.frame(cbind(yhat_mod1,yhat_mod2,yhat_pert_mod1,yhat_pert_mod2)) # build a dataframe with the vector of the predicted values with non-perturbed data and the vectors of the predicted values with perturbed data

attach(jack.mat)

delta<-function(z,jack.mat){RGR(jack.mat[z,1],jack.mat[z,3])-RGR(jack.mat[z,2],jack.mat[z,4])} # function for computing the difference between the RGR associated with the two compared models

results<-jackknife(1:n,delta,jack.mat) # results related to the Jackknife estimation
names(results) # assign the names to the elements of the object "results"

se<-results[1]$jack.se # standard error of the jackknife estimator
z<-(RGR(yhat_mod1,yhat_pert_mod1)-RGR(yhat,yhat_pert_mod2))/se # test statistic
p_value<-2*pnorm(-abs(z)) # p-value


#################################
######## EXPLAINABILITY #########
#################################
### RANK GRADUATION EXPLAINABILITY (RGE) MEASURE ###

# Function for the RGEstar (Rank Graduation Explainability) measure computation
# Inputs: yhat -> predictions generated by the applied full model on non-perturbed data; yhat_xk -> predictions generated by the reduced model without the k-th predictor

RGEstar<-function(yhat,yhat_xk){   
  ryhat_xk<-rank(round(yhat_xk,4),ties.method="min") # ranks of the predicted values
  support<-tapply(yhat,ryhat_xk,mean) # replace the observed target variable value corresponding to the same predictive values with their mean 
  rord<-c(1:length(yhat))   
  for(jj in 1:length(yhat))
  {
    rord[jj]<-support[names(support)==ryhat_xk[jj]] 
  }  
  yhatstar<-rord[order(yhat_xk)] # re-order the observed target variable values with respect to the corresponding predicted values
  I<-1:length(yhatstar) 
  conc<-2*sum(I*yhatstar) # first term of the RGEstar numerator (concordance)
  dec<-2*sum(I*sort(yhat,decreasing=TRUE)) # second term of the RGEstar numerator and denominator (dual Lorenz)
  inc<-2*sum(I*sort(yhat)) # first term of the RGEstar denominator (Lorenz)
  RGEstar<-(conc-dec)/(inc-dec)
  RGEstar
}

RGE<-1-RGEstar(yhat,yhat_xk)

####################################################################################################################################################################################################################

# RGEstar based test for comparing the ordering of the ranks related to the full model with that of the
# reduced model without the predictor of interest
library(bootstrap) # package needed for the jackknife estimation

RGEstar_num<-function(yhat,yhat_xk){   
  ryhat_xk<-rank(round(yhat_xk,4),ties.method="min") # ranks of the predicted values
  support<-tapply(yhat,ryhat_xk,mean) # replace the observed target variable value corresponding to the same predictive values with their mean 
  rord<-c(1:length(yhat))   
  for(jj in 1:length(yhat))
  {
    rord[jj]<-support[names(support)==ryhat_xk[jj]] 
  }  
  yhatstar<-rord[order(yhat_xk)] # re-order the full model predicted values with respect to the corresponding reduced model predicted values
  I<-1:length(yhatstar) 
  conc<-2*sum(I*yhatstar) # first term of the RGEstar numerator (concordance)
  dec<-2*sum(I*sort(yhat,decreasing=TRUE)) # second term of the RGEstar numerator and denominator (dual Lorenz)
  inc<-2*sum(I*sort(yhat)) # first term of the RGEstar denominator (Lorenz)
  RGEstar_num<-(conc-dec)
  RGEstar_num
}

RGEstar_den<-function(yhat){
  I<-1:length(yhat) 
  dec<-2*sum(I*sort(yhat,decreasing=TRUE)) # second term of the RGEstar numerator and denominator (dual Lorenz)
  inc<-2*sum(I*sort(yhat)) # first term of the RGEstar denominator (Lorenz)
  RGEstar_den<-(inc-dec)
  RGEstar_den
  }

n<-length(yhat) # number of observations in the test dataset

jack.mat<-data.frame(cbind(yhat,yhat_xk)) # build a dataframe with the vector of the predicted values of the full model with and the vector of the predicted values on the reduced model

attach(jack.mat)

delta<-function(z,jack.mat){RGEstar_den(jack.mat[z,1])-RGEstar_num(jack.mat[z,1],jack.mat[z,2])} # function for computing the difference between the ranking of the full model and that of the reduced model

results<-jackknife(1:n,delta,jack.mat) # results related to the Jackknife estimation
names(results) # assign the names to the elements of the object "results"

se<-results[1]$jack.se # standard error of the jackknife estimator
z<-(RGEstar_den(yhat)-RGEstar_num(yhat,yhat_xk))/se # test statistic
p_value<-2*pnorm(-abs(z)) # p-value


###########################
######## FAIRNESS #########
###########################
### RANK GRADUATION FAIRNESS (RGF) MEASURE ###

# Function for the RGFstar (Rank Graduation Fairness) measure computation
# Inputs: yhat -> predictions generated by the applied full model on non-perturbed data; yhat_xg -> predictions generated by the reduced model without the g-th group variable

RGF<-function(yhat,yhat_xg){   
  ryhat_xg<-rank(round(yhat_xg,4),ties.method="min") # ranks of the predicted values
  support<-tapply(yhat,ryhat_xg,mean) # replace the full model predicted values corresponding to the same reduced model predictive values with their mean
  rord<-c(1:length(yhat))   
  for(jj in 1:length(yhat))
  {
    rord[jj]<-support[names(support)==ryhat_xg[jj]] 
  }  
  yhatstar<-rord[order(yhat_xg)] # re-order the full model predicted values with respect to the corresponding reduced model predicted values
  I<-1:length(yhatstar) 
  conc<-2*sum(I*yhatstar) # first term of the RGEstar numerator (concordance)
  dec<-2*sum(I*sort(yhat,decreasing=TRUE)) # second term of the RGEstar numerator and denominator (dual Lorenz)
  inc<-2*sum(I*sort(yhat)) # first term of the RGEstar denominator (Lorenz)
  RGFstar<-(conc-dec)/(inc-dec)
  RGFstar
}

####################################################################################################################################################################################################################

# RGFstar based test for comparing the ordering of the ranks related to the full model with that of the
# reduced model without the group variable of interest
library(bootstrap) # package needed for the jackknife estimation

RGFstar_num<-function(yhat,yhat_xg){   
  ryhat_xg<-rank(round(yhat_xg,4),ties.method="min") # ranks of the predicted values
  support<-tapply(yhat,ryhat_xg,mean) # replace the full model predicted values corresponding to the same reduced model predictive values with their mean 
  rord<-c(1:length(yhat))   
  for(jj in 1:length(yhat))
  {
    rord[jj]<-support[names(support)==ryhat_xg[jj]] 
  }  
  yhatstar<-rord[order(yhat_xg)] # re-order the observed target variable values with respect to the corresponding predicted values
  I<-1:length(yhatstar) 
  conc<-2*sum(I*yhatstar) # first term of the RGEstar numerator (concordance)
  dec<-2*sum(I*sort(yhat,decreasing=TRUE)) # second term of the RGEstar numerator and denominator (dual Lorenz)
  inc<-2*sum(I*sort(yhat)) # first term of the RGEstar denominator (Lorenz)
  RGFstar_num<-(conc-dec)
  RGFstar_num
}

RGFstar_den<-function(yhat){
  I<-1:length(yhat) 
  dec<-2*sum(I*sort(yhat,decreasing=TRUE)) # second term of the RGEstar numerator and denominator (dual Lorenz)
  inc<-2*sum(I*sort(yhat)) # first term of the RGEstar denominator (Lorenz)
  RGFstar_den<-(inc-dec)
  RGFstar_den
}

n<-length(yhat) # number of observations in the test dataset

jack.mat<-data.frame(cbind(yhat,yhat_xg)) # build a dataframe with the vector of the predicted values of the full model with and the vector of the predicted values on the reduced model

attach(jack.mat)

delta<-function(z,jack.mat){RGFstar_den(jack.mat[z,1])-RGFstar_num(jack.mat[z,1],jack.mat[z,2])} # function for computing the difference between the ranking of the full model and that of the reduced model

results<-jackknife(1:n,delta,jack.mat) # results related to the Jackknife estimation
names(results) # assign the names to the elements of the object "results"

se<-results[1]$jack.se # standard error of the jackknife estimator
z<-(RGFstar_den(yhat)-RGFstar_num(yhat,yhat_xg))/se # test statistic
p_value<-2*pnorm(-abs(z)) # p-value


