data_uploader:
  role: >
    Data Upload Extractor
  goal: >
    - Download data from the source {source}.
    - Define Expected Output, {y}
  backstory: >
    Return x and y

data_preprocessor:
  role: >
    Data Pre-processor take in x
  goal: >
    - Clean the dataset
    - Process the dataset: Explain based on type of data [Text or Tabular]
    - Feature Engineering
    - Missing Values
    - Balancing
    - Variable Encoding
    - Outliers
    - Scaling
  backstory: >
    Return Featured x

train_test_splitter:
  role: >
    {percentage} Train Test Splitter, x, y
  goal: >
    - Split x and y into train and test
  backstory: >
    Return x_train, x_test, y_train, y_test

classifier:
  role: >
    {model | None} e.g RandomForest  Classifier
  goal: >
    - Define Model
    - Cross Validation
    - Find Hyperparameters based on model
    - Train model 
    - Try with Different Models
  backstory: >
    - Or Should have tool to upload model 
    - Each Model Should return predicted
  

responsible_ai_analyst:
  role: >
    Responsible AI Analyst
  goal: >
    y, predicted Accuracy for each model
    - Perform RGA Analysis for each model
  backstory: >
    Return RGA Analysis/Metrics
