import pandas as pd
import numpy as np
from check_accuracy import rga
from util.utils import find_xtest


def rge(xtrain, xtest, yhat, model, variables= np.nan, method= "single"):
    """
    RANK GRADUATION EXPLAINABILITY (RGE) MEASURE
    Function for the RGE measure computation

    Inputs:
    xtrain : Train data
    xtest : Test data
    yhat : Predicted values generated by the full model including all the explanatory variables 
    model : Model fitted to xtrain and ytrain.
    variables : Variables for which the contribution to the model predictions is found
    method : The method either "single" or "group" is used by the function. If it is "single" the 
    contribution of each single variable is measured while if it is "group", the contribution of the 
    variables, all together, is found.

    Returns:
    RGE  : Calculated RGE measure
    """ 
    # Check the method value
    if method not in ["single", "group"]:
        raise ValueError("method parameter must be either 'single' or 'group'")
           
    # Convert inputs to DataFrames and concatenate them
    xtrain = pd.DataFrame(xtrain).reset_index(drop= True)
    xtest = pd.DataFrame(xtest).reset_index(drop= True)
    yhat = pd.DataFrame(yhat).reset_index(drop=True)

    # When variables are specified and the method is single
    if (variables is not np.nan) and (method == "single"):

        # Variables should be a list
        if not isinstance(variables, list):
            raise ValueError("Variables input must be a list")
        # Check it if the variable is available in data
        for var in variables:
            if var not in xtrain.columns:
                raise ValueError(f"{var} is not in the variables")
            
        rge_list = []
        for i in variables:
            xtest_rm = find_xtest(xtrain, xtest, i)
            yhat_rm = [x[1] for x in model.predict_proba(xtest_rm)]
            rge_list.append(1-(rga(yhat, yhat_rm)))

        rge_df = pd.DataFrame(rge_list, index= list(variables), columns=["RGE"]).sort_values(by="RGE", ascending=False)
        return rge_df

    # When variables are specified and the method is group
    elif (variables is not np.nan) and (method == "group"):

         # Variables should be a list
        if not isinstance(variables, list):
            raise ValueError("Variables input must be a list")
        # Check it if the variable is available in data
        for var in variables:
            if var not in xtrain.columns:
                raise ValueError(f"{var} is not in the variables")
        for i in variables:
            xtest_rm = find_xtest(xtrain, xtest, i)

        yhat_rm = [x[1] for x in model.predict_proba(xtest_rm)]

        rge = 1-(rga(yhat, yhat_rm))
        rge_df = pd.DataFrame(rge, index=[str(variables)], columns=["RGE"])
        return rge_df

    # when variables are not specified and method is single
    elif (variables is np.nan) and (method == "single"):
        rge_list = []
        for i in xtest.columns:
            xtest_rm = find_xtest(xtrain, xtest, i)
            
            yhat_rm = [x[1] for x in model.predict_proba(xtest_rm)] 
            rge_list.append(1-(rga(yhat, yhat_rm)))        
        rge_df = pd.DataFrame(rge_list, index= xtest.columns, columns=["RGE"]).sort_values(by="RGE", ascending=False)
        return rge_df