import pandas as pd
import numpy as np
from check_accuracy import rga
from util.utils import find_xtest

def rgf(xtrain, xtest, ytest, yhat, model, protectedvariable, method= "replacement"):
    """
    RANK GRADUATION FAIRNESS (RGF) MEASURE 
    Function for the RGF measure computation 

    Inputs:
    xtrain : Train data
    xtest : Test data
    ytest : Actual values of the target variable in test data
    yhat : Predicted values generated by the full model including all the explanatory variables 
    model : Model fitted to xtrain and ytrain.
    protectedvariable : The sensitive variable
    method : The method either "replacement" or "parity" is used by the function. If it is "replacement"
    all observations are considered in the unpriviledged group. When it is "parity", RGA of the model is
    compared across the protected groups.

    Returns:
    RGF  : Calculated RGF measure
    """ 

    # Check it if the protected variable is available in data
    if protectedvariable not in xtrain.columns:
        raise ValueError(f"{protectedvariable} is not in the variables")

    # Check the value for method
    if method.lower() not in ["replacement", "parity"]:
        raise ValueError("method can be either replacement or parity")
            
    # Convert inputs to DataFrames and concatenate them
    xtrain = pd.DataFrame(xtrain).reset_index(drop= True)
    xtest = pd.DataFrame(xtest).reset_index(drop= True)
    ytest =pd.DataFrame(ytest).reset_index(drop= True)
    yhat = pd.DataFrame(yhat).reset_index(drop=True)

    # when method is equal to "replacement"
    if method == "replacement":
        xtest_pr = find_xtest(xtrain, xtest, protectedvariable)
        yhat_pr = [x[1] for x in model.predict_proba(xtest_pr)]
        rgf_value = rga(yhat, yhat_pr)
        return pd.DataFrame(rgf_value, index=[protectedvariable], columns=["RGF"])

    else:

        protected_groups = xtrain[protectedvariable].value_counts().index
        rgas = []
        for i in protected_groups:
            xtest_pr = xtest[xtest[protectedvariable]== i]
            ytest_pr = ytest.loc[xtest_pr.index]
            yhat_pr = [x[1] for x in model.predict_proba(xtest_pr)]
            rga_value = rga(yhat, yhat_pr)
            rgas.append(rga_value)            
        return pd.DataFrame(rgas, index=protected_groups, columns=["RGA"])

